name: Test and Build

on: [push, pull_request, workflow_dispatch]

jobs:
  test_and_build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: ./.github/workflows/test.yml
    - uses: ./.github/workflows/build.yml